### ISSUE TITLE
command not found: vue

### ISSUE THREAD

**Issue by pablopaul** [codecept-js/vue-cli-plugin-codeceptjs-puppeteer#4]
After running `vue invoke vue-cli-plugin-codeceptjs-puppeteer --save-dev` I get the following error:

```js
zsh: command not found: vue
```

Note that the vue docs does not recommend to install vue globally by default, see https://vuejs.org/v2/guide/installation.html#NPM

**Comment by DavertMik** [comment]
Updated readme
