### ISSUE TITLE
Unclear Readme

### ISSUE THREAD

**Issue by pablopaul** [codecept-js/vue-cli-plugin-codeceptjs-puppeteer#5]
The readme says:

> Should we add a test component so you could see how to interact with elements in your tests? Agree, if you start with an empty project & you don't mind we update your App.js & main.js files to add a test component.

I dont understand this clearly, does it mean that `vue invoke vue-cli-plugin-codeceptjs-puppeteer --save-dev` will add a test component if execured in an vue empty project context?

**Comment by DavertMik** [comment]
Updated readme
